"""feedback consolidated proposal ids

Revision ID: 4ed436dc1622
Revises: a8f28ca13ed0
Create Date: 2026-06-13 13:10:00.247562

"""
import sqlalchemy as sa

from alembic import op

revision = '4ed436dc1622'
down_revision = 'a8f28ca13ed0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.add_column(sa.Column('proposal_feedback_ids', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.drop_column('proposal_feedback_ids')

    # ### end Alembic commands ###
