"""digest send_no_news column

Revision ID: cdfd1c611254
Revises: b25619e5e161

"""
import sqlalchemy as sa

from alembic import op

revision = 'cdfd1c611254'
down_revision = 'b25619e5e161'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('digests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('send_no_news', sa.Boolean(), nullable=False,
                                      server_default=sa.false()))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('digests', schema=None) as batch_op:
        batch_op.drop_column('send_no_news')

    # ### end Alembic commands ###
